// angular-frontend/src/app/new/new.component.ts
import { Feed } from './../feed/feed';
import { AppRoutingModule } from './../app-routing.module';
import { Component, OnInit ,ViewChild} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';

import {New} from './new';
import { NewService } from './new.service';

@Component({
  selector: 'app-new',
  templateUrl: './new.component.html',
  styleUrls: ['./new.component.css']
})
export class NewComponent implements OnInit {

  model = new  New();
  @ViewChild('fileInput') fileInput;


  constructor( private router: Router,private service : NewService) { }

  ngOnInit() {
  }

  submit(){

    const fileBrowser = this.fileInput.nativeElement; 
    const formData = new FormData();    

        formData.append('image', fileBrowser.files[0]);
        formData.append('author', this.model.author as string);
        formData.append('place', this.model.place as string);
        formData.append('description', this.model.description as string);
        formData.append('hashtags', this.model.hashtags as string);
        console.log(formData);
         this.service.add(formData);
         this.router.navigate(["/Feed"]);   
  }

}

<form id="new-post" (ngSubmit)="submit()">
   
        <input type="file" #fileInput
        name="image"
        [(ngModel)]="model.image"
        onChange={this.handleImageChange}
        />

        <input 
             type="text" 
             id="author"
             name="author"
             placeholder="Autor do post"
             [(ngModel)]="model.author" 
            
         />
        
         <input 
             type="text" 
             id="place"
             name="place" 
             placeholder="Local do post"
             [(ngModel)]="model.place"
         />
    
         <input 
             type="text" 
             id="description"
             name="description" 
             placeholder="Descrição do post"
             [(ngModel)]="model.description"
         />
    
         <input 
             type="text" 
             id="hashtags"
             name="hashtags" 
             placeholder="Hashtags do post"
             [(ngModel)]="model.hashtags"
         />
        
         <button type="submit">Enviar</button>
    </form>

// react-frontend/src/pages/New.js
import React, {Component} from 'react';
import api from '../services/api'
import './New.css'

class   New extends Component {

    state = {
            image:null,
            author:'',
            place :'',
            description:'',
            hashtags:''
    };
    handleSubmit = async e => {
        e.preventDefault();
        const data = new FormData();
        
        data.append('image',this.state.image);
        data.append('author',this.state.author);
        data.append('place',this.state.place);
        data.append('description',this.state.description);
        data.append('hashtags',this.state.hashtags);

        await api.post('posts',data);

        this.props.history.push('/');

    }
    handleChange = e => {
        this.setState({ [e.target.name] : [e.target.value]})
    }

    handleImageChange = e=>{
        this.setState({ image: e.target.files[0]});
    }
 render(){
            return(
               <form id="new-post" onSubmit={this.handleSubmit}>
                   <input type="file" 
                        onChange={this.handleImageChange}
                   />

                   <input 
                        type="text" 
                        name="author" 
                        placeholder="Autor do post"
                        onChange={this.handleChange}
                        value={this.state.author}
                    />

                    <input 
                        type="text" 
                        name="place" 
                        placeholder="Local do post"
                        onChange={this.handleChange}
                        value={this.state.place}
                    />

                    <input 
                        type="text" 
                        name="description" 
                        placeholder="Descrição do post"
                        onChange={this.handleChange}
                        value={this.state.description}
                    />

                    <input 
                        type="text" 
                        name="hashtags" 
                        placeholder="Hashtags do post"
                        onChange={this.handleChange}
                        value={this.state.hashtags}
                    />

                    <button type="submit">Enviar</button>
               </form>
            );

        }
}

export default New;
