// react-frontend/src/pages/Feed.js
import React, {Component} from 'react';
import api from '../services/api';
import io  from 'socket.io-client';
import './Feed.css';

import  more  from '../assets/more.svg';
import  like  from '../assets/like.svg';
import  comment  from '../assets/comment.svg';
import  send  from '../assets/send.svg';

class   Feed extends Component {
  
  state = {
      feed : [],
  };

    async componentDidMount(){
        this.registerToSocket();

         const response = await api.get('posts');
         
         this.setState({
             feed:response.data
         });
         
    }

    registerToSocket = () => {
        const socket = io('http://localhost:3333');



    socket.on('post', newPost => {
        this.setState({ feed : [newPost, ...this.state.feed]});
    });

    socket.on('like', likePost => {
        this.setState({ feed : this.state.feed.map(post =>
            post._id ===likePost._id ? likePost : post
            )
        });
    });

    }

    handlerLike = id =>{
        console.log(id);
        api.post(`posts/${id}/like`);

    }

 render(){
  return(
     <section id="post-list">
        {
            this.state.feed.map( post => (
                <article key={post._id}>
                <header>
                    <div className="user-info">
                       <span>{post.author} </span>
                       <span className="place"> {post.place}</span>
                    </div>
                  
                    <img src={more} alt="Mais"/>
                </header>
               
                <img src={`http://localhost:3333/files/${post.image}`}/>
                
                <footer>
                   <div className="actions">
                       <button type="button" onClick={ () =>this.handlerLike(post._id)}>
                       <img src={like} />
                       </button>
                       <img src={comment}/>
                       <img src={send}/>
                   </div>     
                 
                   <strong>{post.likes}</strong>
                  
                   <p> 
                       {post.description}
                        <span> {post.hashtags}</span> 
                   </p>  
                  
                </footer>
   
            </article>
           
            ))
        }
     </section>
  );
 }
}

export default Feed;

// angular-frontend/src/app/feed/feed.component.ts
import { Component, OnInit } from '@angular/core';

import {FeedService } from './feed.service';
import {Feed} from './feed'

@Component({
  selector: 'app-feed',
  templateUrl: './feed.component.html',
  styleUrls: ['./feed.component.css'],
  providers: [FeedService]
})
export class FeedComponent implements OnInit {

  posts :Feed[] = [];
  connection;
  post :Feed;

  constructor(private service : FeedService) { 

  }

  ngOnInit() {


    this.service.getList().subscribe(data => this.posts = data,err => {
      alert('Aconteceu um erro!');
    });


    this.connection = this.service.list().subscribe(post => {
      this.posts = [post, ...this.posts];      
    });

    this.connection = this.service.like().subscribe(likePost  => {
      this.posts = this.posts.map(post => post._id === likePost._id ? likePost : post);    
    });



  }

  handlerLike(id){
    this.service.addLike(id);
  }

}

<section id="post-list">
          <article *ngFor="let post of posts">
          <header>
              <div class="user-info">
                 <span> {{ post.author }} </span>
                 <span class="place"> {{post.place}}</span>
              </div>            
              <img src="assets/more.svg" alt="Mais"/>
          </header>         
          <img src="http://localhost:3333/files/{{post.image}}"/>          
          <footer>
             <div class="actions">
                 <button type="button"  (click)="handlerLike(post._id)" >
                 <img src="assets/like.svg" />
                 </button>
                 <img src="assets/comment.svg"/>
                 <img src="assets/send.svg"/>
             </div>    
             <strong>{{post.likes}}</strong>            
             <p> 
                 {{post.description}}
                  <span> {{post.hashtags}}</span> 
             </p>              
          </footer>
      </article>     
</section>
